### ISSUE TITLE
aux_estimate, mean, sum_first_moment explanation

### ISSUE THREAD

**Issue by HenryPengZou** [eth-sri/probabilistic-forecasts-attacks#4]
https://github.com/eth-sri/probabilistic-forecasts-attacks/blob/df78ffd7375089bb7b38fbf55bb840b7699365eb/Finance/attack/attack_modules.py#L299-L317

Hi, could you provide some explanation for the 'aux_estimate, mean, sum_first_moment' here?

It would be great if you can give both some description and math formula/definition of these three variables here.

I appreciate your work!

**Comment by rdang-nhu** [comment]
Hi. `sum_first_moment` is defined as
<img width="432" alt="Screenshot 2021-07-23 at 11 41 01" src="https://user-images.githubusercontent.com/18661420/126764659-3c5c4879-1f69-4fce-b9d7-01ee31874e14.png">
`aux_estimate` is defined as
<img width="809" alt="Screenshot 2021-07-23 at 11 45 02" src="https://user-images.githubusercontent.com/18661420/126765103-63c66870-273f-4af9-94a0-f731f6e0da5b.png">

`sum_weights` is defined as
<img width="351" alt="Screenshot 2021-07-23 at 11 41 25" src="https://user-images.githubusercontent.com/18661420/126764678-be1b60c4-a91c-45d7-ab1d-77ee87fd25e1.png">
All these are parts of the gradient estimators described in [the paper](https://arxiv.org/pdf/2003.03778.pdf).

**Comment by HenryPengZou** [comment]
Thank you!
